import com.sun.javafx.binding.StringFormatter;
import jdk.jfr.events.ExceptionThrownEvent;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        String inputPath = args[0];
        String outputPath = args[1];
        String transform = args[2];
        BufferedImage file = null;
        try {
            System.out.println("Reading in the file...");
            file = ImageIO.read(new File(inputPath));
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        Bitmap bitmap = new Bitmap(file);
        switch (transform) {
            case "randomize":
                System.out.println("Performing transform \"" + transform + "\" on file.");
                bitmap.randomize();
                break;
            case "rotate":
                System.out.println("Performing transform \"" + transform + "\" on file.");
//                    bitmap.rotate();
                break;
            case "mirrorHorizontal":
                System.out.println("Performing transform \"" + transform + "\" on file.");
                bitmap.mirrorHorizontal();
                break;
            case "grayscale":
                System.out.println("Performing transform \"" + transform + "\" on file.");
                bitmap.grayscale();
                break;
            case "deepfry":
                System.out.println("Performing transform \"" + transform + "\" on file.");
                bitmap.deepfry();
                break;
            default:
                break;
        }
        bitmap.output(outputPath);
        System.out.println("Transform successfully completed.");
    }
}
