import jdk.jfr.events.ExceptionThrownEvent;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        try {
            String inputPath = args[0];
            String outputPath = args[1];
            String transform = args[2];
            BufferedImage file = ImageIO.read(new File(inputPath));
            Bitmap bitmap = new Bitmap(file);
            switch (transform) {
                case "randomize":
                    bitmap.randomize();
                    break;
                case "rotate":
//                    bitmap.rotate();
                    break;
                case "mirrorHorizontal":
//                    bitmap.mirrorHorizontal();
                    break;
                case "deepfry":
                    bitmap.deepfry();
                default:
                    break;
            }
            bitmap.output(outputPath);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
}
