import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static void main(String[] args) {
        String inputPath = args[0];
        String outputPath = args[1];
        String transform = args[2];
        BufferedImage file = ImageIO.read(new File(inputPath));
        Bitmap bitmap = new Bitmap(file);
        switch (transform) {
            case "flip":
                bitmap.flip();
                break;
            case "rotate":
                bitmap.rotate();
                break;
            case "mirrorHorizontal":
                bitmap.mirrorHorizontal();
                break;
            default:
                break;
        }
        bitmap.output(outputPath);
    }
}
